[package]
name = "iced_memory_editor"
version = "0.1.0"
authors = ["LLeny"]
edition = "2021"
description = "A memory editor for the iced library"
readme = "README.md"
homepage = "https://github.com/LLeny/iced_memory_editor"
repository = "https://github.com/LLeny/iced_memory_editor"
license = "GPLv3"
keywords = ["iced", "memory", "editor", "rust"]
categories = ["gui"]

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", features = ["advanced", "svg"] }
bytemuck = "1.22.0"

[dev-dependencies]
rand = "0.9"

[lib]
name = "iced_memory_editor"
path = "src/lib.rs"

[[example]]
name = "memory_editor"
path = "examples/memory_editor.rs"
